Public Class Form1

    Private Sub Button1_Click(sender As System.Object, e As System.EventArgs) Handles Button1.Click
        Do
            Do
                Do
                    Do
                        Do
                            Do
                                Do
                                    Do
                                        Do
                                            Do
                                                Do
                                                    Do
                                                        Do
                                                            Do
                                                                Do
                                                                    Do
                                                                        Do
                                                                            Do
                                                                                Do
                                                                                    Do
                                                                                        Do
                                                                                            Do
                                                                                                Do
                                                                                                    Do
                                                                                                        Do
                                                                                                            Do
                                                                                                                Do
                                                                                                                    Do
                                                                                                                        Do
                                                                                                                            Do
                                                                                                                                Do
                                                                                                                                    Do
                                                                                                                                        Do
                                                                                                                                            Do
                                                                                                                                                Do
                                                                                                                                                    Do
                                                                                                                                                        Do
                                                                                                                                                            Do
                                                                                                                                                                Do
                                                                                                                                                                    Do
                                                                                                                                                                        Do
                                                                                                                                                                            Do
                                                                                                                                                                                Do
                                                                                                                                                                                    Do
                                                                                                                                                                                        Do
                                                                                                                                                                                            Do
                                                                                                                                                                                                Do
                                                                                                                                                                                                    Do
                                                                                                                                                                                                        Do
                                                                                                                                                                                                            Do
                                                                                                                                                                                                                Do
                                                                                                                                                                                                                    Do
                                                                                                                                                                                                                        Do
                                                                                                                                                                                                                            Do
                                                                                                                                                                                                                                Do
                                                                                                                                                                                                                                    Do
                                                                                                                                                                                                                                        Do
                                                                                                                                                                                                                                            Do
                                                                                                                                                                                                                                                Do
                                                                                                                                                                                                                                                    Do
                                                                                                                                                                                                                                                        Do
                                                                                                                                                                                                                                                            Do
                                                                                                                                                                                                                                                                Do
                                                                                                                                                                                                                                                                    Do
                                                                                                                                                                                                                                                                        Do
                                                                                                                                                                                                                                                                            Do
                                                                                                                                                                                                                                                                                TextBox1.Text = ("Hello")

                                                                                                                                                                                                                                                                            Loop
                                                                                                                                                                                                                                                                        Loop
                                                                                                                                                                                                                                                                    Loop
                                                                                                                                                                                                                                                                Loop
                                                                                                                                                                                                                                                            Loop
                                                                                                                                                                                                                                                        Loop
                                                                                                                                                                                                                                                    Loop

                                                                                                                                                                                                                                                Loop
                                                                                                                                                                                                                                            Loop
                                                                                                                                                                                                                                        Loop
                                                                                                                                                                                                                                    Loop
                                                                                                                                                                                                                                Loop
                                                                                                                                                                                                                            Loop
                                                                                                                                                                                                                        Loop
                                                                                                                                                                                                                    Loop
                                                                                                                                                                                                                Loop
                                                                                                                                                                                                            Loop
                                                                                                                                                                                                        Loop

                                                                                                                                                                                                    Loop
                                                                                                                                                                                                Loop
                                                                                                                                                                                            Loop
                                                                                                                                                                                        Loop
                                                                                                                                                                                    Loop

                                                                                                                                                                                Loop
                                                                                                                                                                            Loop
                                                                                                                                                                        Loop
                                                                                                                                                                    Loop
                                                                                                                                                                Loop
                                                                                                                                                            Loop
                                                                                                                                                        Loop
                                                                                                                                                    Loop
                                                                                                                                                Loop
                                                                                                                                            Loop
                                                                                                                                        Loop
                                                                                                                                    Loop
                                                                                                                                Loop
                                                                                                                            Loop
                                                                                                                        Loop
                                                                                                                    Loop
                                                                                                                Loop
                                                                                                            Loop
                                                                                                        Loop
                                                                                                    Loop
                                                                                                Loop
                                                                                            Loop
                                                                                        Loop
                                                                                    Loop
                                                                                Loop
                                                                                TextBox1.Text = ("hello")

                                                                            Loop
                                                                        Loop
                                                                    Loop
                                                                Loop
                                                            Loop
                                                        Loop
                                                    Loop
                                                Loop
                                            Loop
                                        Loop
                                    Loop
                                Loop
                            Loop
                        Loop
                    Loop
                Loop
            Loop
        Loop
    End Sub
End Class
